### ISSUE TITLE
Fehlermeldung „URL is invalid“

### ISSUE THREAD

**Issue by Eeewald85** [trbnhck/scriptable-scripts#4]
Hallo,

seit heute erscheint beim Widget und beim direkten Aufrufen des Scripts in Scriptable bei mir die Fehlermeldung „Error: The URL is invalid“. Beim Tippen auf das Widget wird aber nach wie vor die Tagesschau Website aufgerufen. 

Gibts einen Trick, wie man das wieder hinbekommt?

![AE855D22-CD4E-4154-A238-150F04B35A11](https://user-images.githubusercontent.com/73432625/99786455-d0fa2600-2b1e-11eb-9e25-eae51211b371.jpeg)

**Comment by trbnhck** [comment]
Sollte mit 56d4aa1a2ae388bfe552852d58fcec009cbcb8b5 gefixed :)
